# Generated by Django 4.2.15 on 2024-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_id'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kept_movies',
            field=models.ManyToManyField(related_name='kept_by_users', to='movies.movie'),
        ),
    ]
